In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b=np.array([[1,2,3],[1,2,3]])
print(b)

[[1 2 3]
 [1 2 3]]


In [3]:
c=np.array([[[1,2,3],[1,2,4],[1,2,4]]])
print(c)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [4]:
d=np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
print(d)
print(type(d))

[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]
<class 'numpy.ndarray'>


In [5]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


1
2
3
4


In [7]:
a=np.array([1,2,3,4,5,6,7],ndmin=6)
print(a)

[[[[[[1 2 3 4 5 6 7]]]]]]


In [8]:
print(b[0])

[1 2 3]


In [10]:
print(b[0,2])

3


In [14]:
print(c[0,2])

[1 2 3]


In [15]:
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x[1,1,2])

12


In [16]:
y=np.array([[8,8,8],[9,9,9]])
print(y[0,-3])

8


In [17]:
v=np.array([1,2,3,4,5,6,7,8,9])
print(v[2:7])

[3 4 5 6 7]


In [19]:
print(v[1:])

[2 3 4 5 6 7 8 9]


In [20]:
print(v[:3])

[1 2 3]


In [21]:
print(v[1:6:3])

[2 5]


In [27]:
r=np.array([[6,7,8,9,10],[11,12,13,14,15]])
print(r[1, 0:3])

[11 12 13]


In [26]:
print(r[0:4 ,3])

[ 9 14]


In [40]:
z=np.array([1,2,3,4,5])
x=z.copy()
x[4]=9
print(z)
print(x)

[1 2 3 4 5]
[1 2 3 4 9]


In [41]:
u=z.view()
u[4]=13
print(z)
print(u)

[ 1  2  3  4 13]
[ 1  2  3  4 13]


In [43]:
g=np.array([[[1,6,7],[2,3,4],[6,8,9]]])
for x in np.nditer(g):
    print(x)

1
6
7
2
3
4
6
8
9


In [49]:
h=np.array([1,2,3,4,5,6,7,8,9])
for x in np.ndenumerate(h):
    print(x)

((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)
((4,), 5)
((5,), 6)
((6,), 7)
((7,), 8)
((8,), 9)
